### ISSUE TITLE
Nothing showing up....

### ISSUE THREAD

**Issue by rogueops** [sjinks/roundcube_recaptcha#5]
Did all the steps, have the keys in the config and Google Recaptcha is showing up? Repo does not really say if it is always suppose to be there on every login or if it shows up after invalid login attempts.

**Comment by 1kUHuiswkvj7spRO** [comment]
It will always appear.

**Comment by rogueops** [comment]
Not sure where I went wrong then, ill double check everything again

**Comment by rogueops** [comment]
Found the issue, when you git clone the repo the folder name is roundcube_recaptcha so nothing works even if setup since I am guessing the name within the code that is hard coded is called recaptcha so i mv'd the folder and names it recaptcha and when refreshing it appeared and showed the checkbox.
